# DOMAIN OF AI

1) Expert Systems
-> An expert systems are AI programs that simulate the decision-making ability of a human expert. They use a knowledge base and rules to solve complex problems in a specific domain. These systems are used in medical diagnosis, finance, and technical support. Example:- Dendral, Mycin, DXplain.

2) Robotics
-> Robotics is the field of AI that deals with designing and developing intelligent robots. These robots can perform tasks automatically by sensing their environment and making decisions. Robotics is used in manufacturing, healthcare, and space exploration.

3) Machine Learning
-> Machine Learning is a branch of AI that allows computers to learn from data and improve their performance without being explicitly programmed. Algorithms analyze patterns in data and make predictions or decisions. It is used in recommendation systems, spam filtering, and fraud detection.

4) Natural Language Processing
-> Natural Language Processing (NLP) enables computers to understand, interpret, and generate human language. It helps machines read text, understand speech, and respond in natural language. Applications include chatbots, language translation, and voice assistants. Example:- Alexa, Siri.

5) Fuzzy Logic
-> Fuzzy Logic is an AI technique that deals with uncertain or approximate reasoning instead of fixed true or false values. In classical logic, values are either 0 (false) or 1 (true), but in fuzzy logic values can be between 0 and 1. It helps machines make decisions similar to human thinking.

6) Neural Network/ Deep Learning
-> Deep learning is a type of machine learning based on artificial neural networks in which multiple layers of processing are used to extract higher level features from data.These techniques are used in image recognition, speech recognition, and self-driving cars.

# 8 PUZZLE PROBLEM

The 8 puzzle consists of eight numbered, movable tile set in a 3x3 frame. One cell of the frame is always empty thus making it possible to move an adjacent numbered tile into the empty cell.Such a puzzle is illustrated in following diagram.

# Rules of the Puzzle

- Only one tile can be moved at a time.

- A tile can move up, down, left, or right.

- A tile can move only into the blank space.

- The aim is to reach the goal state arrangement.

Initial state
|2|8|3|                                            
|-|-|-|                                           
|1|6|4|        
|7|_|5|                           

Goal state
|1|2|3|                                            
|-|-|-|                                           
|8|_|4|        
|7|6|5|

# Step-by-Step Solution
Step 1 – Move 6 Down
|2|8|3|
|-|-|-| 
|1|_|4|        
|7|6|5|

Tile 6 moves down into the blank space.

Step 2 – Move 1 Right
|2|8|3|
|-|-|-| 
|_|1|4|        
|7|6|5|

Tile 1 moves right into the blank space.

Step 3 – Move 2 Down
|_|8|3|
|-|-|-| 
|2|1|4|        
|7|6|5|

Tile 2 moves down.

Step 4 – Move 8 Left
|8|_|3|
|-|-|-| 
|2|1|4|        
|7|6|5|

Tile 8 moves left into the blank space.

Step 5 – Move 1 Up
|8|1|3|
|-|-|-| 
|2|_|4|        
|7|6|5|

Tile 1 moves up.

Step 6 – Move 2 Right
|8|1|3|
|-|-|-| 
|_|2|4|        
|7|6|5|

Tile 2 moves right.

Step 7 – Move 8 Down
|_|1|3|
|-|-|-| 
|8|2|4|        
|7|6|5|

Tile 8 moves down.

Step 8 – Move 1 Left
|1|_|3|
|-|-|-| 
|8|2|4|        
|7|6|5|

Tile 1 moves left.

Step 9 – Move 2 Up
|1|2|3|
|-|-|-| 
|8|_|4|        
|7|6|5|

Now the puzzle reaches the goal state.

# Final Goal State
|1|2|3|
|-|-|-| 
|8|_|4|        
|7|6|5|

The 8 Puzzle Problem demonstrates how search algorithms in AI find a sequence of moves from the initial state to the goal state.
By moving tiles step by step using the blank space, the system reaches the desired arrangement.

# WATER JUG PROBLEM

- You are given two jugs, 4-ltr and 3-ltr.
- Neither jug has any measuring markings on it.
- A pump which has unlimited water which you can choose to fill the jug.
- How can you get exactly 2 ltr of water in a 4 tr jug?
- We will represent a state of the problem as a tuple(x,y).
- x = amount of water in the 4 ltr jug
- y = amount of water in the 3 ltr jug
1) Initial state : (0,0); 0<=x<=4, and 0<=x<=3.
2) Goal state : (2,n) for any value of n.


# Production Rules
|Sr. | Current State | Next State | Description|
|------|--------|---------|--------|
|1 | (x,y) if x<4| (4,y) | Fill the 4-ltr jug|
|2 | (x,y) if y<3| (x,3) | Fill the 3-ltr jug|
|3| (x,y) if x>0| (x-d,y) | Pour some water out of the 4-ltr jug|
|4| (x,y) if y>0| (x,y-d) | Pour some water out of the 3-ltr jug|
|5| (x,y) if x>0| (0,y) | Empty the 4-ltr jug on the ground|
|6| (x,y) if y>0| (x,0) | Empty the 3-ltr jug on the ground|
|7| (x,y) i fx+y>=4 & y>0| (4,y-(4-x)) | Pour water from the 3-ltr jug into the 4-ltr jug until the 4-ltr jug is full|
|8| (x,y) if x+y>=3 & x>0| (x-(3-y),3) | Pour water from the 4-ltr jug into the 3-ltr jug until the 3-ltr jug is full|
|9| (x,y) if x+y<=4 & y>0| (x+y,0) | Pour all the water from the 3-ltr jug into the  4-ltr jug|
|10| (x,y) if x+y<=3 & x>0| (0,x+y) | Pour all the water from the 4-ltr jug into the  3-ltr jug|
|11| (0,2) | (2,0) | Pour the 2-ltr from the 3-ltr jug into the  4-ltr jug|
|12| (2,y) | (0,y) | Empty the 2-ltr in the 4-ltr on the ground|

# Productions for the water jug
|4-ltr | 3-ltr | rule applied|
|------|--------|---------|
|0 | 0| 0 |
|0 | 3|2|
|3| 0| 9|
|3| 3|2|
|4| 2| 7|
|0| 2| 5 or 12|
|2| 0| 9 or 11|

In [3]:
import pandas as pd
import numpy as np


df = pd.read_csv("Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
df.shape

(150, 6)

In [6]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [7]:
df=df.dropna()

In [8]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species              str
dtype: object

In [9]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [10]:
df["petal_size"] = df["PetalLengthCm"].apply(
lambda x: "Large" if x > 4 else "Small"
)
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,petal_size
0,1,5.1,3.5,1.4,0.2,Iris-setosa,Small
1,2,4.9,3.0,1.4,0.2,Iris-setosa,Small
2,3,4.7,3.2,1.3,0.2,Iris-setosa,Small
3,4,4.6,3.1,1.5,0.2,Iris-setosa,Small
4,5,5.0,3.6,1.4,0.2,Iris-setosa,Small

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Species"] = le.fit_transform(df["Species"])
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,petal_size
0,1,5.1,3.5,1.4,0.2,0,Small
1,2,4.9,3.0,1.4,0.2,0,Small
2,3,4.7,3.2,1.3,0.2,0,Small
3,4,4.6,3.1,1.5,0.2,0,Small
4,5,5.0,3.6,1.4,0.2,0,Small